//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexHero.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegexHero.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;html&gt;
        ///	&lt;head&gt;&lt;title&gt;
        ///	RegExLib.com Regular Expression Cheat Sheet (.NET Framework)
        ///&lt;/title&gt;&lt;link href=&quot;App_Themes/Green/default.css&quot; type=&quot;text/css&quot; rel=&quot;stylesheet&quot; /&gt;&lt;link href=&quot;App_Themes/Green/Form.css&quot; type=&quot;text/css&quot; rel=&quot;stylesheet&quot; /&gt;&lt;link href=&quot;App_Themes/Green/Tester.css&quot; type=&quot;text/css&quot; rel=&quot;stylesheet&quot; /&gt;&lt;/head&gt;
        ///	&lt;body class=&quot;whiteBg&quot;&gt;
        ///	&lt;table class=&quot;pageTop outerTable&quot;&gt;
        ///		&lt;tr&gt;
        ///			&lt;td class=&quot;imageCell&quot;&gt;
        ///				&lt;a href=&quot;http://regexlib.com/&quot;&gt;&lt;img src=&quot;App_Themes/Green/Images/RegExLib_logo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string example1 {
            get {
                return ResourceManager.GetString("example1", resourceCulture);
            }
        }
    }
}
